Repository katkes/SOEN-343-Project, pull requests merged in 2025-03, with the labels that each got.

#12 Stripe API Integration
  backend/.env.example
  backend/package-lock.json
  backend/package.json
  backend/src/configs/env.ts
  backend/src/server.ts
  backend/src/services/stripe/StripeFacade.ts
  docs/backend/3.env-vars.md
  docs/backend/index.md
Labels: documentation, task

#19 Purchase Event Ticket Stripe Implementation
  backend/src/controllers/payment.ts
  backend/src/middleware/.gitkeep
  backend/src/models/event.ts
  backend/src/routes/api.ts
  backend/src/routes/payment.ts
  backend/src/services/mongo/ticket.ts
  backend/src/services/stripe/.gitkeep
  backend/src/services/stripe/StripeFacade.ts
  frontend/src/pages/EventRegistration.tsx
Labels: enhancement, task

#31 17 conditional rendering in dashboard
  backend/src/controllers/auth.ts
  backend/src/controllers/company.ts
  backend/src/controllers/user.ts
  backend/src/middleware/auth.ts
  backend/src/middleware/session.ts
  backend/src/models/company.ts
  backend/src/models/user.ts
  backend/src/routes/auth.ts
  backend/src/services/mongo/company.ts
  backend/src/services/mongo/user.ts
  backend/src/ts-types.d.ts
  frontend/package-lock.json
  frontend/src/App.tsx
  frontend/src/components/NavBar.tsx
  frontend/src/hooks/useAccountInfo.ts
  frontend/src/pages/Dashboard.tsx
  frontend/src/pages/EventOrganizerSignUp.tsx
  frontend/src/pages/SponsorSignUp.tsx
  frontend/src/pages/routes.ts
  frontend/src/services/backend/api.ts
  frontend/src/services/backend/auth.ts
  frontend/src/services/backend/endpoints.ts
  frontend/src/stores/.gitkeep
  frontend/src/stores/accountStore.ts
  frontend/src/stores/keys.ts
  frontend/src/types/account.ts
  frontend/src/types/auth.ts
  frontend/src/types/observable.ts
Labels: enhancement

#36 User Profile Management
  backend/src/controllers/user.ts
  backend/src/routes/user.ts
  frontend/src/App.tsx
  frontend/src/components/EventForm.tsx
  frontend/src/components/Sidebar.tsx
  frontend/src/pages/EditProfile.tsx
  frontend/src/pages/Profile.tsx
  frontend/src/pages/routes.ts
Labels: enhancement
